### ISSUE TITLE
Untrack __pycache__

### ISSUE THREAD

**Issue by impredicative** [wutianyiRosun/CGNet#1]
The `__pycache__` directory should never be tracked in and added to git. It is to be ignored from git using a `.gitignore` file. Please add such a file and untrack all added instances of `__pycache__`.

**Comment by wutianyiRosun** [comment]
nice, thx u~

**Comment by wutianyiRosun** [comment]
> The `__pycache__` directory should never be tracked in and added to git. It is to be ignored from git using a `.gitignore` file. Please add such a file and untrack all added instances of `__pycache__`.

nice, thx u~
