### ISSUE TITLE
can i do inference using CPU

### ISSUE THREAD

**Issue by jiaobingle** [wutianyiRosun/CGNet#15]
Getting error while running cityscapes_evl.py on Cityscape Data set

when i run with "--gpu 0" , it shows "RuntimeError: CUDA error: out of memory", because of my 2GB GPU. and then, i run without "--cuda " or "--gpu" ,it also looks like "RuntimeError: CUDA error: out of memory",so how can i do test or eval using CPU, thx!

**Comment by wutianyiRosun** [comment]
@jiaobingle U can refer to the Pytorch official example, and learn how to run the model on the cpu.
