### ISSUE TITLE
*gtFine_labelTrainIds.png

### ISSUE THREAD

**Issue by leonzfa** [wutianyiRosun/CGNet#16]
I can't find where is the "*gtFine_labelTrainIds.png" file in the list file. The dataset I downloaded from CityScapes only contains "*gtFine_labelIds.png". Where can I get the "*gtFine_labelTrainIds.png" files? Thanks.

**Comment by wutianyiRosun** [comment]
You need to use a script to convert the labelID to the trainID

**Comment by wutianyiRosun** [comment]
@leonzfa , you need to use a script to convert the labelID to the trainID
