### ISSUE TITLE
I think the codes about flops dosen't  compute the AdaptiveAvgPool2d 's ops!

### ISSUE THREAD

**Issue by monk42** [wutianyiRosun/CGNet#17]

**Comment by monk42** [comment]
if isinstance(net, torch.nn.MaxPool2d) or isinstance(net, torch.nn.AvgPool2d):
       net.register_forward_hook(pooling_hook)

**Comment by wutianyiRosun** [comment]
＠monk42 thx u,

**Comment by ABDULMAWLA** [comment]
i face the same problem
