### ISSUE TITLE
about cityscapes_inform.pkl

### ISSUE THREAD

**Issue by tianwen0110** [wutianyiRosun/CGNet#18]
Thanks for sharing your codes!
But I have a question! I can't find "cityscapes_inform.pkl" in the folder, and also the folder "./dataset/wtfile" is not exist. How can I get this file ?

**Comment by tianwen0110** [comment]
sorry, I

**Comment by jwnirvana** [comment]
could you tell how to solve the problem, please

**Comment by xiaoyufenfei** [comment]
Hi, tianwen0110 and jwnirvana,
 I also have a question! How generate the "cityscapes_inform.pkl" file according to a dataset?
Thank you all !

**Comment by KazusaW1999** [comment]
Hi, how did you solve it? I got a same problem..
