### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './dataset/wtfile/camvid_inform.pkl'

### ISSUE THREAD

**Issue by jwnirvana** [wutianyiRosun/CGNet#19]
hello,could you give some suggestions to this problem,please?

**Comment by jwnirvana** [comment]
sorry,please ignore the problem

**Comment by KazusaW1999** [comment]
Hi, how did you solve it? I got a same problem..

**Comment by She-yh** [comment]
Hello, I've got the same problem. How did you solve it?
