### ISSUE TITLE
Speed Question(Wrong Speed Test)

### ISSUE THREAD

**Issue by lxtGH** [wutianyiRosun/CGNet#2]
Hi!! Thanks for sharing your codes.
I have seen your result in your paper about bi-seg. I tried to reproduce the result of bi-seg, however I only got 71%IOU（single scale）, have you **successfully** got 74% IOU results on that? May be he use ms test.
what is your advantages compared with bi-seg? More Light (Less memory cost)?

**Comment by lxtGH** [comment]
There are two problems:
1. I test your model with 1024 * 2048 as input images. However I **only** got  9 fps on single 1080TI. 
I use the code like the following
start = time.time()
out = model(img)
torch.cuda.synchronize()
print('Speed: {} fps.'.format(1.0/(time.time()-start)))
2. In your paper, ICnet only 16 fps which is not consistent with his paper. (30 fps)
I don't why. The gap between K80 and 1080TI is such large ??

**Comment by yun-liu** [comment]
@lxtGH 您好，碰到了同样的问题，请问您重现出论文中的速度了吗？

**Comment by lxtGH** [comment]
I think it is wrong speed testing.

**Comment by lxtGH** [comment]
Hi , @wutianyiRosun 
Did you use this line ?  
torch.cuda.synchronize() for speed test?

**Comment by yyfyan** [comment]
@lxtGH @wutianyiRosun 
I have a problem:
Pytorch DwConv's implement is not good,it's very slow. The CGNet'paper result is based on Pytorch?

**Comment by lxtGH** [comment]
@wutianyiRosun If you didn't use the line of code, your speed reported in your paper is wrong.
@yyfyan What speed results you get ?

**Comment by Reagan1311** [comment]
I got the same result as you, a single 1080Ti got about 9 FPS. @lxtGH 
And if I didn't use **torch.cuda.synchronize()**
The FPS will increase to ~70Fps, this code is necessary.

**Comment by lxtGH** [comment]
@Reagan1311 Yes, GPU and CPU must synchronize (CPU must wait until the end of GPU forwarding )

**Comment by meteorshowers** [comment]
10FPS only! I test it on 1080Ti.
I suggest that you change your arxive paper.

**Comment by LinZhuoChen** [comment]
I met the same question. I hope I can get an answer. Thank you.

**Comment by wutianyiRosun** [comment]
@meteorshowers, @LinZhuoChen  We will update in the next few days.
