### ISSUE TITLE
No such file or directory: './dataset/wtfile/camvid_inform.pkl'

### ISSUE THREAD

**Issue by wk524629918** [wutianyiRosun/CGNet#23]
How can I get this file?

**Comment by FCinHFUT** [comment]
hi, I have the same problem when run the cityscapes_train.py .    Have you solved this problem??

**Comment by wk524629918** [comment]
> 嗨，我在运行城市景观_train.py时遇到同样的问题。您解决了这个问题吗？

I didn't solve it

**Comment by KazusaW1999** [comment]
Hi, how did you solve it? I got a same problem..
