### ISSUE TITLE
ContextNet: 66.1% accuracy, 0.8 million params and 41.9 fps

### ISSUE THREAD

**Issue by rudrapoudel** [wutianyiRosun/CGNet#3]
Congratulations for nice work.

Have you also seen BMVC 2018 paper, ContextNet with 0.8 million parameter yield 66.1% accuracy and runs in 41.9 fps in the oldest Titan X gpu?

**Comment by wutianyiRosun** [comment]
Hi, rudrapoudel
  Thank you for your recommendation, I am going to understand the ContextNet.

**Comment by bhack** [comment]
@rudrapoudel Is it your work?

**Comment by bhack** [comment]
I see an early implementation at https://github.com/klickmal/ContextNet but I don't think it is related to @rudrapoudel or co-authors.

**Comment by rudrapoudel** [comment]
Hi, we will release the code in the first half of the Jan. Which I will announce in my twitter account- http://twitter.com/RudraPoudel

**Comment by rudrapoudel** [comment]
Finally: Tensorflow code is here: https://www.toshiba.eu/eu/Cambridge-Research-Laboratory/Computer-Vision/Resources/ContextNet/
