### ISSUE TITLE
关于cityscape数据集重新训练效果

### ISSUE THREAD

**Issue by Vipermdl** [wutianyiRosun/CGNet#7]
我尝试使用您的代码重新训练了cityscape多次，在测试集上的结果只能达到54%，也尝试过使用您所训练好的模型在验证集上测试，如文章中所说可以取得64%miou。我在阅读您所提供的代码中发现以下问题：
1.你所使用的种子为随机种子。
2.你的dataloader中最终提供的数据类型为numpy，并没有将其转换为tensor格式。（你在cityscape_train文件中声明了transform，但是并没有使用）。
您所提供的代码并非您最终的实验代码。在确定CGNet结构的形式之后，我并没有跑出这个结果的原因主要是因为什么？

**Comment by yun-liu** [comment]
@Vipermdl @wutianyiRosun 您好，碰到了同样的问题，请问您重现出论文中的结果了吗？
