### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by yyfyan** [wutianyiRosun/CGNet#8]
I noted that in the code:
image = image[:, :, ::-1]  
image -= self.mean
but,cv2.imread's image format is BGR,and self.mean also is BGR ,why need to convert the format image[:, :, ::-1].

**Comment by yyfyan** [comment]
torchvision's model use RGB,so if use Opencv read image,need to do: image = image[:, :, ::-1]

**Comment by yun-liu** [comment]
@yyfyan Hello, but I still do not understand why the code subtracts the self.mean of BGR format from the image of RGB format. Is it not consistent?

**Comment by wutianyiRosun** [comment]
@yyfyan great, thanks for your reminder. I believe it will bring performance improvements by solving this bug.

**Comment by Reagan1311** [comment]
I think we need to exchange the sequence of these two lines, first BGR image subtracts the BGR mean, and then convert the format to RGB, right?. @yyfyan
